version: 2
updates:
  # 📦 Updates root-level dependencies
  - package-ecosystem: 'pip'
    commit-message:
      prefix: ⬆
    directory: '/'
    reviewers:
      - 'ramironunes'
    schedule:
      interval: 'monthly'
