fail_fast: true

repos:
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        description: "Run 'mypy' for static type checking"
        entry: mypy
        language: python
        types: [python]
        args: []
        stages: [pre-commit]

      - id: ruff
        name: ruff
        description: "Run 'ruff' for linting Python code at high speed"
        entry: ruff check --force-exclude --fix
        language: python
        types_or: [python, pyi]
        args: []
        require_serial: true
        stages: [pre-commit]

      - id: ruff-format
        name: ruff-format
        description: "Format Python files using 'ruff format' for consistency"
        entry: ruff format --force-exclude
        language: system
        types_or: [python, pyi]
        args: []
        require_serial: true
        stages: [pre-commit]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: \.(css|graphql|gql|html|json|js|jsx|less|md|scss|ts|tsx|ya?ml)$
        exclude: (package|tslint|package-lock|en|pt|.*test.*)\.json|test-setup.ts$|(\/dist\/)
        additional_dependencies:
          - prettier@2.8.8
          - 'prettier-plugin-sort-json@2.0.0'
          - '@trivago/prettier-plugin-sort-imports@4.3.0'

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-yaml
        args:
          - --unsafe
      - id: end-of-file-fixer
      - id: trailing-whitespace
